try
a0=get(a,'Value');
b0=get(b,'Value');
catch
    a0=0.5;
    b0=0.5;
    end
a = uicontrol('Style','slider','Min',-5,'Max',5,...
                'SliderStep',[0.01 0.01],'Value',a0,...
                'Position',[80 20 200 20],...
                'CallBack',@(hObj,eventdata) get(hObj,'Value'));
b = uicontrol('Style','slider','Min',-5,'Max',5,...
                'SliderStep',[0.01 0.01],'Value',b0,...
                'Position',[80 40 200 20],...
                'CallBack',@(hObj,eventdata) get(hObj,'Value'));
anumber = uicontrol('style','text', ...
    'string','0', ...
   'fontsize',12, ...
   'position',[0,20,50,20]);
bnumber = uicontrol('style','text', ...
    'string','0', ...
   'fontsize',12, ...
   'position',[0,40,50,20]);
